### PR TITLE
fixes to Larch.pm for Windows

### PR DESCRIPTION
**Pull request by newville**
This now allows Larch to work as backend on Windows as well as unixy systems.  It does test for larch_server *without*  specifying the version of python, which works on all systems I've tested, and should also work on all Linuxes.

For Windows, Perl5.18 seems to not have a sufficient version of RPC::XML::Client, but using Strawberry Perl 5.24 did work.

### CODE REVIEW

**Comment by newville** [comment]
@bruceravel  This will now find `larch_server` from PATH, from a single-file larch installer, or from larch an Anaconda environment.  It does work (for me anyway) on Windows and Mac too.

**Comment by newville** [comment]
@bruceravel Well "works" in the sense that Athena finds and runs the correct larch_server.  On Windows, I'm seeing an error on importing data... will investigate.

**Comment by newville** [comment]
@bruceravel I verified that I could get an error reading data on MacOSX as well, but also verified that

- I can read at least 10 different files, with several different column layouts
- Larch.pm does pass its self test, which does read a data file (the same datafile) and runs through the steps of basic processing and autobk, repeating 400 times.

So I think the Larch interface itself is fine, but there may be a problem using the Larch backend to read some files.  Anyway, this is far ahead of the master branch and ready to merge.

**Comment by bruceravel** [comment]
Awesome.  Very excited about this.  I have a mountain of demeter chores for the shutdown, which starts next week.

**Pull request merged**
