### PR TITLE
Possible typo converting Siegbahn and IUPAC notations for characteristic lines

### PR DESCRIPTION
**Pull request by iangodfrey**
According to (Page 744) https://www.iupac.org/publications/pac/pdf/1991/pdf/6305x0735.pdf, and others, Mz is M4,5-N2,3, not N6,7

### CODE REVIEW

**Comment by bruceravel** [comment]
I am floored!  Such attention to detail!

Thanks for finding and correcting that.  You're the :bomb:

**Comment by newville** [comment]
@iangodfrey @bruceravel  Thanks -- this mistake is in XrayDB and Xray Larch.  It seems it is in the original Elam database.

**Comment by bruceravel** [comment]
@iangodfrey @newville : I exchanged email with Tim Elam.  He doesn't remember any reason for identifying the M&zeta; transition as he did and suspects it is simply a mistake.  He's working on [this thing](http://mars.nasa.gov/mars2020/mission/instruments/pixl/) (which is totally amazing) and planning on making some updates to his database.  He said he'd keep me posted -- I'll make sure that any updates get propagated through all our software.

**Comment by newville** [comment]
@bruceravel @iangodfrey  I also updated this for the sqlite version of this data at  https://github.com/scikit-beam/XrayDB   See: https://github.com/scikit-beam/XrayDB/pull/15

**Comment by iangodfrey** [comment]
Well, who'd have thought there'd be so much behind a simple typo!

On a related note, I don't recall thanking Bruce for fixing the issue with the data smoothing tool I reported a while ago, so thanks for that!

**Pull request merged**
